### ISSUE TITLE
Forhåndsvisning på Facebook

### ISSUE THREAD

**Issue by PetterFlottum** [Haakenlid/tassendesken#10]
Det er ingen forhåndsvisning av bilder på Facebook nå. Vet ikke hva grunnen er, men gjør at det kan se litt rart ut og at ejg ikke får valgt alternative bilder

**Comment by Haakenlid** [comment]
Vet ikke hva feilen er, men det ser ut til at det funker av og til og av og til ikke. Jeg mistenker at feilen er hos facebook. Kanskje opplegget for å hente inn bilder hos facebook er litt overbelasta av og til? 

Forøvrig så er dette ikke repoen for nettsida. Bruk https://github.com/Haakenlid/tassen/ i stedet.

**Comment by PetterFlottum** [comment]
Aha, beklager!


20. mai 2015 kl. 15.28 skrev Håken Lid <notifications@github.com>:

**Comment by Haakenlid** [comment]
Har gjort en liten endring i hovedbildet til facebook. Nå blir det laget i
det formatet som facebook bruker dvs. 600x315 px

Jeg har forøvrig ikke funnet grunnen til at det ikke dukker opp
forhåndsvisning. Forhåpentligvis er det noe som går over.


2015-05-20 15:29 GMT+02:00 PetterFlottum <notifications@github.com>:

> Aha, beklager!
>
>
> 20. mai 2015 kl. 15.28 skrev Håken Lid <notifications@github.com>:
>
> > Vet ikke hva feilen er, men det ser ut til at det funker av og til og av
> > og til ikke. Jeg mistenker at feilen er hos facebook. Kanskje opplegget
> for
> > å hente inn bilder hos facebook er litt overbelasta av og til?
> >
> > Forøvrig så er dette ikke repoen for nettsida. Bruk
> > https://github.com/Haakenlid/tassen/ i stedet.
> >
> > —
> > Reply to this email directly or view it on GitHub
> > <
> https://github.com/Haakenlid/tassendesken/issues/10#issuecomment-103889002
> >
>
> > .
> >
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/Haakenlid/tassendesken/issues/10#issuecomment-103889291>
> .
>



-- 
Håken Lid
