### ISSUE TITLE
Scriptet for å lagre bilder funker ikke

### ISSUE THREAD

**Issue by hadahva** [Haakenlid/tassendesken#6]
Etter at univ-desken ble flyttet til et annet sted, har ikke scriptet for å lagre bilder fra photoshop funket.

**Comment by hadahva** [comment]
Hei! Har du mulighet til å se på scriptet en gang i nær framtid? Vi begynner opp igjen for fullt med foto på tirsdag, og det er litt tungvint å lagre bildene manuelt. Testa det nettopp, og det kommer fortsatt opp feilmelding.

**Comment by Haakenlid** [comment]
Har endret flere av skriptene på desken nå, også bildelagringa. Sjekk at det er oppdatert når du logger deg inn. En ting som er endret er at filnavn nå kun skal inneholder bindestrek - i stedet for underscore _.

**Comment by hadahva** [comment]
Nå har jeg oppdaget to nye bugs i skriptet:
1) Det går ikke an å lagre bilder med skriptet uten å koble til sak. Det er ikke krise, men hadde vært kjekt.
2) Det går ikke an å bla nedover i sakene i skriptet, så det er mange saker som er umulige å velge.

To bugs som egentlig ikke er så alvorlige, men som blir litt dumme når man kombinerer dem, siden man da blir nødt til å lagre en del bilder manuelt..

**Comment by Haakenlid** [comment]
Jeg åpner en ny issue på det i stedet #7
