### ISSUE TITLE
Photoshop-krøll

### ISSUE THREAD

**Issue by Haakenlid** [Haakenlid/tassendesken#7]
Nå har jeg oppdaget to nye bugs i skriptet:
1) Det går ikke an å lagre bilder med skriptet uten å koble til sak. Det er ikke krise, men hadde vært kjekt.
2) Det går ikke an å bla nedover i sakene i skriptet, så det er mange saker som er umulige å velge.

To bugs som egentlig ikke er så alvorlige, men som blir litt dumme når man kombinerer dem, siden man da blir nødt til å lagre en del bilder manuelt..

**Comment by Haakenlid** [comment]
> 1) Det går ikke an å lagre bilder med skriptet uten å koble til sak. Det er ikke krise, men hadde vært kjekt.

Hvordan går det ikke an? Hva skjer når du prøver å gjøre det?

> 2) Det går ikke an å bla nedover i sakene i skriptet, så det er mange saker som er umulige å velge.

Hvordan ser det ut? Dukker rullefeltet opp?

**Comment by hadahva** [comment]
1)
Når du trykker "ikke koble til sak" og fyller inn initialer, tittel og seksjon, skjer det ingenting. Det går ikke an å huke av bilder, og det går ikke an å trykke "ok" (de er grå).
2)
Rullefeltet dukker opp, men når du ruller ned går det ikke nedover. Men det har bare vært et problem en gang, jeg tror faktisk ikke det er et stort problem med mindre det er veldig mange saker.

**Comment by Haakenlid** [comment]
Skjønner. Skal se på det neste gang jeg er innom kontoret. Det er nok ikke så vanskelig å få fikset, men må nok teste det ut på riktig versjon av photoshop for å være sikker på at det funker som det skal.

**Comment by Haakenlid** [comment]
Dette skal være løst nå. Tror også jeg fant ut hvorfor alle skript kjører så tregt på TASSENPROD2.
